repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.2.0
      hooks:
          - id: setup-cfg-fmt
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports
            args: [--py311-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.4.0
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
